replicaCount: 1

image:
  repository: 281981892670.dkr.ecr.eu-central-1.amazonaws.com/eks-ai-playground-faceapp
  tag: "15bffec65383eef4626431d3f2f4f0f265f27363"

service:
  port: 8000

resources:
  requests:
    cpu: "1"
    memory: 2Gi
  limits:
    cpu: "2"
    memory: 4Gi
    nvidia.com/gpu: "1"

pvc:
  size: 2Gi
