apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ollama.fullname" . }}-config
  labels:
    {{- include "ollama.labels" . | nindent 4 }}
data:
  keep-alive: {{ .Values.ollamaKeepAlive | quote }}
